---
Name: jabber
After: 'framework/*','cms/*'
---
Member:
    extensions:
        - JabberMemberExtension
Group:
    extensions:
        - JabberGroupExtension
Page_Controller:
    extensions:
        - JabberPageExtension
